// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3mHowCiKi6o37Q9wZfUJfYhCPNDgCmXA',
    appId: '1:775309713100:web:571fef41a9d0c00f696c69',
    messagingSenderId: '775309713100',
    projectId: 'myportfolio-be9a6',
    authDomain: 'myportfolio-be9a6.firebaseapp.com',
    storageBucket: 'myportfolio-be9a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-rB0wZJ57m6bUeXJByEwJedkV6Vo_T9k',
    appId: '1:775309713100:android:2950ef10c04baec9696c69',
    messagingSenderId: '775309713100',
    projectId: 'myportfolio-be9a6',
    storageBucket: 'myportfolio-be9a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA28SIILxnKmJHI6iGmMnSsEHNE27vMtfg',
    appId: '1:775309713100:ios:85266d29385bb2c4696c69',
    messagingSenderId: '775309713100',
    projectId: 'myportfolio-be9a6',
    storageBucket: 'myportfolio-be9a6.firebasestorage.app',
    iosBundleId: 'com.example.myPortfolio',
  );
}
